system:
    port: 49090
    socket_timeout: 10

    initial_delay_on_failure: 120
    max_delay_on_failure: 900
    delay_inc_div: 5

    check_for_updates: True
    check_for_updates_channel:
      - development
      - stable
    check_for_updates_interval: 3600

Sample-Router:
    enabled: False

    hostname: localhost

    username: username
    password: password

    use_ssl: False
    no_ssl_certificate: False
    ssl_certificate_verify: False

    polling_interval: 10
    slow_polling_interval: 60

    collectors:
      - dhcp
      - system_resource
      - health
      - interface
      - firewall_filter
      - firewall_mangle
      - ipv6_firewall_filter
      - ipv6_firewall_mangle
      - ipv6_neighbor
      - wifi_clients
      - netwatch
      - arp
      - user
      - queue_simple
      - queue_tree
      - wireguard_peers

    slow_collectors:
      - route
      - ipv6_route
      - installed_packages
      - interface_monitor
      - capsman
      - identity
      - wifi
      - public_ip
      - wireguard

